services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Alpdesk\AlpdeskParallax\Listener\HooksListener:
    arguments:
      - '@request_stack'
      - '@contao.routing.scope_matcher'
      - '%kernel.project_dir%'
      - '@assets.packages'
      - '@contao.image.factory'
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
      - { name: contao.hook, hook: compileArticle, method: onCompileArticle, priority: 0 }
